
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parDer = 46;
  public static final int mayorQue = 31;
  public static final int llaveAbre = 47;
  public static final int print_ = 61;
  public static final int menosMenos = 20;
  public static final int dosPuntos = 43;
  public static final int masMas = 19;
  public static final int false_ = 8;
  public static final int char_ = 15;
  public static final int graficar_dot = 63;
  public static final int null_ = 18;
  public static final int switch_ = 56;
  public static final int do_ = 55;
  public static final int coma = 41;
  public static final int igual = 44;
  public static final int llaveCierre = 48;
  public static final int this_ = 22;
  public static final int double_ = 14;
  public static final int diferenteIgual = 36;
  public static final int caracter = 5;
  public static final int menorQue = 32;
  public static final int menorIgual = 34;
  public static final int println_ = 62;
  public static final int dividido = 28;
  public static final int graficar_env = 50;
  public static final int import_ = 49;
  public static final int corcheteAbre = 23;
  public static final int else_ = 52;
  public static final int case_ = 57;
  public static final int corcheteCierre = 24;
  public static final int menos = 26;
  public static final int void_ = 9;
  public static final int EOF = 0;
  public static final int int_ = 13;
  public static final int class_ = 11;
  public static final int mas = 25;
  public static final int mayorIgual = 33;
  public static final int error = 1;
  public static final int true_ = 7;
  public static final int doble = 4;
  public static final int if_ = 51;
  public static final int or = 38;
  public static final int entero = 3;
  public static final int while_ = 54;
  public static final int parIzq = 45;
  public static final int return_ = 10;
  public static final int por = 27;
  public static final int punto = 12;
  public static final int new_ = 21;
  public static final int xor = 39;
  public static final int potencia = 29;
  public static final int id = 6;
  public static final int break_ = 59;
  public static final int puntoComa = 42;
  public static final int string_ = 16;
  public static final int igualIgual = 35;
  public static final int for_ = 53;
  public static final int not = 40;
  public static final int and = 37;
  public static final int default_ = 58;
  public static final int continue_ = 60;
  public static final int modulo = 30;
  public static final int cadena = 2;
  public static final int boolean_ = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cadena",
  "entero",
  "doble",
  "caracter",
  "id",
  "true_",
  "false_",
  "void_",
  "return_",
  "class_",
  "punto",
  "int_",
  "double_",
  "char_",
  "string_",
  "boolean_",
  "null_",
  "masMas",
  "menosMenos",
  "new_",
  "this_",
  "corcheteAbre",
  "corcheteCierre",
  "mas",
  "menos",
  "por",
  "dividido",
  "potencia",
  "modulo",
  "mayorQue",
  "menorQue",
  "mayorIgual",
  "menorIgual",
  "igualIgual",
  "diferenteIgual",
  "and",
  "or",
  "xor",
  "not",
  "coma",
  "puntoComa",
  "dosPuntos",
  "igual",
  "parIzq",
  "parDer",
  "llaveAbre",
  "llaveCierre",
  "import_",
  "graficar_env",
  "if_",
  "else_",
  "for_",
  "while_",
  "do_",
  "switch_",
  "case_",
  "default_",
  "break_",
  "continue_",
  "print_",
  "println_",
  "graficar_dot"
  };
}

